### ISSUE TITLE
rcutfac

### ISSUE THREAD

**Issue by yanxon** [materialsvirtuallab/veidt#37]
https://github.com/materialsvirtuallab/veidt/blob/68037e596d2d1bf1682ca35d08c50c7782dfa637/veidt/potential/lammps/calcs.py#L277

The first argument in the format is ***self.rcutfac***, isn't it?

**Comment by YunxingZuo** [comment]
Thanks so much for your comment. The "rcutfac" argument in the SpectralNeighborAnalysis class is essentially the global cutoff distance, hence the **self.rcutfac** is the absolute cutoff radii. 
Here the 1 is the scale factor applied to all cutoff radii which is consistent with the grammar in LAMMPS. We decided not to scale cutoff radii so that we apply no influence to the absolute cutoff radii.

**Comment by yanxon** [comment]
:+1:  Thank you for your explanation, @YunxingZuo.
